apiVersion: v1
kind: Service
metadata:
  name: simulator
spec:
  type: NodePort
  selector:
    app: restoringvalues
  ports:
    - port: 8092
      targetPort: 8092
      nodePort: 30092
